name: mad_inclass_activity_9
description: A Halloween storybook app with spooky sounds.
version: 1.0.0

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1

flutter:
  assets:
    - assets/images/
    - assets/sounds/
